[project]
name = "notion-charts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=1.1.1,<2.0",
    "markupsafe==2.0.1",
    "requests>=2.32.3",
    "setuptools>=75.7.0",
    "werkzeug<2.0",
]

